Feat/output card
camilocoelhogomes/insumos_react_native pull request #6
Opened 2021-10-07 17:42 UTC by camilocoelhogomes

Implementado o estilo dos cards de saida, precisa de algumas revisões de correção nas fórmula

2021-10-07 17:45 UTC, camilocoelhogomes commented
App is ready for review, you can [see it here](https://expo.dev/@bycedric/use-expo?release-channel=pr-6).

2021-10-07 17:50 UTC, camilocoelhogomes commented
Já percebi que não ta dando scroll na tela, vou tentar configurar isso

2021-10-08 14:59 UTC, Mplorosa reviewed
O output card está com quebra de texto entre a informação e o resultado, o que leva a alteração na formatação de texto da ferramenta, podendo causar desconforto na leitura da informação. Além disso, há necessidade de retrabalhar a chave "Possuo Análise de Solo" que não altera em nada a ela do aplicativo.

2021-10-08 15:03 UTC, camilocoelhogomes commented
> O output card está com quebra de texto entre a informação e o resultado, o que leva a alteração na formatação de texto da ferramenta, podendo causar desconforto na leitura da informação. Além disso, há necessidade de retrabalhar a chave "Possuo Análise de Solo" que não altera em nada a ela do aplicativo.

Decidi manter a quegra de linha para não ter que diminuir o tamanho da fonte e as informções caberem em uma unica linha

2021-10-08 15:06 UTC, Mplorosa requested changes
Alteração de unidade de peso para intervalos iniciais de 0 - 999 gramas e 0 - 999 kg.

2021-10-12 13:12 UTC, camilocoelhogomes commented
> e t

Agora a chave altera o aplicativo, coloquei todos as saídas em linha, Lucas, da uma conferida na UX desse output card, e vê se consegue dar uma melhorada nela

2021-10-14 14:09 UTC, merged